-- phpMyAdmin SQL Dump
-- version 5.2.1
-- https://www.phpmyadmin.net/
--
-- Host: 127.0.0.1
-- Generation Time: May 15, 2025 at 02:37 PM
-- Server version: 10.4.32-MariaDB
-- PHP Version: 8.2.12

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `luxtech`
--

-- --------------------------------------------------------

--
-- Table structure for table `admin`
--

CREATE TABLE `admin` (
  `id` int(11) UNSIGNED NOT NULL,
  `username` varchar(60) NOT NULL,
  `password` varchar(100) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `admin`
--

INSERT INTO `admin` (`id`, `username`, `password`) VALUES
(1, 'gilang', '$2y$10$JjFJ2nsAUPcBuXZWp/kKLuUEwGTX7rFnG.P1fI0Jyw3WgDaN1gwTy'),
(2, 'Ginpra', '$2y$10$M7WxSDSabkc/FMfdBqKD3u9dqOt3g78T.iAIanob0sjdAthZLwozK'),
(3, 'daniel', '$2y$10$qQ9iMjboPxSmtr.u.fXB0uykGkmhywwsKahpMETlcZbERoSROff6S');

-- --------------------------------------------------------

--
-- Table structure for table `berita`
--

CREATE TABLE `berita` (
  `id` int(11) UNSIGNED NOT NULL,
  `judul` varchar(255) NOT NULL,
  `sub` varchar(255) NOT NULL,
  `deskripsi` text NOT NULL,
  `gambar` varchar(255) DEFAULT NULL,
  `kategori` enum('hot','latest','tips','') NOT NULL,
  `tanggal` date NOT NULL DEFAULT current_timestamp()
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

--
-- Dumping data for table `berita`
--

INSERT INTO `berita` (`id`, `judul`, `sub`, `deskripsi`, `gambar`, `kategori`, `tanggal`) VALUES
(1, 'AI Mengubah Dunia', 'Dari Klinik ke Kelas: Bagaimana Mesin Cerdas Merevolusi Cara Kita Hidup', 'Kecerdasan buatan (AI) kini menjadi kekuatan utama dalam mengubah berbagai aspek kehidupan manusia. Dari sektor kesehatan hingga pendidikan, teknologi ini menghadirkan efisiensi dan solusi inovatif yang sebelumnya sulit dicapai. Di bidang medis, AI mampu membantu dokter dalam mendiagnosis penyakit dengan lebih cepat dan akurat melalui analisis data pasien dan pencitraan medis. Sementara itu, di dunia pendidikan, AI digunakan untuk menciptakan pembelajaran yang dipersonalisasi, sehingga siswa dapat belajar sesuai dengan kemampuan dan kecepatan masing-masing.\r\n\r\nTidak hanya itu, AI juga berdampak besar pada industri dan ekonomi global. Otomatisasi proses produksi dengan bantuan AI telah meningkatkan produktivitas serta mengurangi biaya operasional perusahaan. Di sisi lain, munculnya AI juga menimbulkan tantangan baru, seperti kekhawatiran akan hilangnya lapangan kerja dan isu etika terkait pengambilan keputusan oleh mesin. Oleh karena itu, penting bagi pemerintah dan masyarakat untuk beradaptasi dan merancang kebijakan yang mendukung perkembangan teknologi ini secara bertanggung jawab dan inklusif.', 'img_6820918d9352c.jpg', 'hot', '2025-05-11'),
(2, 'Gebrakan Terbaru NVIDIA: RTX 5060 dan Inovasi AI Mengguncang Dunia Teknologi', 'NVIDIA kembali mencuri perhatian dunia teknologi dengan peluncuran kartu grafis terbarunya, GeForce RTX 5060, yang dijadwalkan rilis pada 19 Mei 2025.', 'NVIDIA kembali mencuri perhatian dunia teknologi dengan peluncuran kartu grafis terbarunya, GeForce RTX 5060, yang dijadwalkan rilis pada 19 Mei 2025. Dibanderol dengan harga $299, RTX 5060 menjadi model entry-level dalam seri RTX 50 yang mengusung arsitektur Blackwell terbaru. Meskipun memiliki 3.840 CUDA cores sekitar 800 lebih sedikit dibandingkan RTX 5060 Ti kartu ini tetap menawarkan fitur canggih seperti memori GDDR7, DLSS 4 dengan Multi Frame Generation, serta peningkatan pada ray tracing dan tensor cores. Beberapa judul game terbaru, termasuk MechWarrior 5: Clans dan New World: Aeternum, telah mengonfirmasi dukungan untuk teknologi DLSS terbaru ini sebelum peluncuran resmi GPU tersebut .\r\n\r\nSelain itu, NVIDIA juga memperkenalkan superkomputer Millennium M2000 yang ditenagai oleh GPU Blackwell terbaru. Superkomputer ini dirancang untuk mempercepat simulasi dalam bidang desain chip, penerbangan, dan bioteknologi. Dengan kemampuan mengurangi waktu simulasi dari delapan hari menjadi kurang dari 24 jam, Millennium M2000 telah menarik perhatian perusahaan besar seperti Boeing dan Boom Supersonic. NVIDIA sendiri berencana membeli 10 unit superkomputer ini untuk pengembangan chip generasi berikutnya dan infrastruktur pusat data AI .\r\n\r\nGebrakan ini menegaskan posisi NVIDIA sebagai pemimpin dalam inovasi teknologi, baik di sektor konsumen maupun industri. Dengan kombinasi produk yang terjangkau dan solusi AI canggih, NVIDIA terus mendorong batas-batas kemungkinan dalam dunia komputasi dan kecerdasan buatan.', 'img_68209ed79ed2c.jpeg', 'hot', '2025-05-11'),
(3, 'Teknologi Quantum Menjadi Sorotan, Siap Ubah Dunia Komputasi Modern', 'Lebih Cepat dari Cahaya? Mengintip Masa Depan Dengan 1.000 Qubit', 'Teknologi komputasi kuantum terus menunjukkan perkembangan signifikan dan digadang-gadang akan menjadi tonggak penting dalam revolusi digital dunia. Perusahaan teknologi global seperti IBM, Google, dan Intel intensif mengembangkan komputer kuantum yang dinilai mampu menyelesaikan perhitungan superkompleks dengan kecepatan jauh melampaui komputer konvensional.\r\n\r\nBaru-baru ini, IBM mengumumkan keberhasilan mereka dalam menciptakan prosesor kuantum bernama Condor, yang memiliki lebih dari 1.000 qubit. Ini merupakan pencapaian penting yang menunjukkan bahwa komputasi kuantum tidak lagi sekadar teori, namun telah mendekati tahap penerapan praktis. \"Condor merupakan langkah penting menuju sistem kuantum yang dapat digunakan untuk menyelesaikan persoalan-persoalan dunia nyata,\" kata perwakilan IBM dalam keterangan resminya.\r\n\r\nTeknologi ini dipercaya akan membawa dampak besar dalam berbagai sektor, seperti pengembangan obat, keamanan siber, keuangan, hingga kecerdasan buatan. Di tengah pesatnya inovasi, sejumlah negara juga berlomba mempercepat investasi di bidang ini, termasuk Indonesia yang mulai menjajaki peluang kolaborasi riset dan pengembangan teknologi kuantum.', 'img_6820a48b5afa2.jpg', 'hot', '2025-05-11'),
(4, 'Google Luncurkan Android 16 dan Android XR, Tandai Era Baru Perangkat Lunak Mobile dan XR', '“Baklava” dan Realitas Campuran: Dua OS Baru yang Bawa Kita ke Dimensi Lain', 'Google resmi meluncurkan Android 16, sistem operasi mobile terbarunya, yang dijadwalkan rilis stabil pada Juni 2025. Android 16, dengan nama kode \"Baklava\", memperkenalkan fitur-fitur baru seperti peningkatan privasi, efisiensi energi, dan integrasi AI yang lebih dalam. Versi beta keempat telah dirilis pada April 2025, menandai kesiapan platform untuk pengembang dan produsen perangkat .\r\n\r\nSelain itu, Google juga mengumumkan Android XR, sistem operasi baru yang dirancang khusus untuk perangkat extended reality (XR). Android XR akan mendukung perangkat seperti headset Samsung Project Moohan dan kacamata pintar Project Astra, dengan integrasi mendalam bersama Gemini, chatbot AI generatif dari Google. Langkah ini menandai komitmen Google dalam memperluas ekosistem perangkat lunak ke ranah realitas campuran .\r\n\r\nKedua peluncuran ini menunjukkan upaya Google dalam memimpin inovasi perangkat lunak, baik di sektor mobile maupun XR, dengan fokus pada integrasi AI dan pengalaman pengguna yang lebih imersif.', 'img_6820a50c85762.jpg', 'latest', '2025-05-11'),
(5, 'Huawei Luncurkan MateBook Pro 2025 dengan Chip Kirin X90, Tantang Dominasi Apple Silicon', 'Kinerja Ultra-Tajam dan Daya Tahan Raksasa: Siapa Lagi yang Butuh Apple?', 'Huawei resmi meluncurkan laptop flagship terbarunya, MateBook Pro 2025, yang ditenagai oleh chip in-house Kirin X90. Langkah ini menandai ambisi Huawei untuk menyaingi dominasi Apple Silicon dalam ekosistem perangkat keras dan lunak terintegrasi. Kirin X90 dirancang khusus untuk memberikan kinerja tinggi dengan efisiensi daya optimal, menjadikannya pesaing serius di pasar laptop premium.\r\n\r\nMateBook Pro 2025 hadir dengan desain ramping dan ringan, serta layar OLED 14 inci beresolusi tinggi. Dengan integrasi penuh antara perangkat keras dan lunak, laptop ini menawarkan pengalaman pengguna yang mulus dan responsif. Huawei juga menyematkan fitur keamanan canggih dan dukungan untuk ekosistem perangkat Huawei lainnya, memperkuat posisinya di pasar global.\r\n\r\nPeluncuran MateBook Pro 2025 dengan Kirin X90 menunjukkan komitmen Huawei untuk berinovasi dan bersaing di tingkat global, menghadirkan alternatif kuat bagi konsumen yang mencari perangkat premium dengan kinerja tinggi dan ekosistem terintegrasi', 'img_6820a5b58b6fa.jpeg', 'latest', '2025-05-11'),
(6, 'Tahun 2025 Menjadi Titik Balik Industri Game: Inovasi dan Rilis Besar Meramaikan Dunia Gaming', 'Dari Naga Siber hingga Lapangan Arena Neon Rasakan Game Teranyar yang Bikin Deg-deg an!', 'Tahun 2025 menjadi momen penting bagi industri game global dengan hadirnya berbagai inovasi dan rilis besar yang dinantikan oleh para gamer. Setelah menghadapi tantangan di tahun-tahun sebelumnya, industri ini kembali bangkit dengan menghadirkan judul-judul baru yang menjanjikan pengalaman bermain yang segar dan mendalam.\r\n\r\nSalah satu sorotan utama adalah perilisan Doom: The Dark Ages oleh id Software dan Bethesda Softworks. Game ini menghadirkan nuansa baru dalam seri Doom dengan latar belakang abad pertengahan dan gameplay yang lebih berat serta strategis. Pemain akan merasakan pertempuran yang intens dengan senjata baru seperti Shield Saw dan Skull Crusher, serta kemampuan mengendarai naga sibernetik dan mech raksasa. Game ini dijadwalkan rilis pada 15 Mei 2025 untuk PlayStation 5, Xbox Series X/S, dan PC. \r\n\r\nNintendo juga tidak ketinggalan dengan memperkenalkan Drag x Drive, sebuah game olahraga futuristik yang menggabungkan elemen basket kursi roda dengan kontrol gerak inovatif menggunakan Joy-Con 2. Game ini dirancang khusus untuk Nintendo Switch 2 dan dijadwalkan rilis pada musim panas 2025. Dengan desain arena neon dan gameplay yang kompetitif, Drag x Drive diharapkan menjadi salah satu game andalan Nintendo tahun ini. \r\n\r\nSelain itu, beberapa game lain yang sangat dinantikan juga akan hadir di tahun ini, seperti Monster Hunter Wilds, Death Stranding 2: On the Beach, dan Borderlands 4. Meskipun Grand Theft Auto VI mengalami penundaan hingga Mei 2026, antusiasme para gamer tetap tinggi terhadap berbagai judul baru yang akan dirilis. \r\n\r\nDengan berbagai inovasi dan rilis besar ini, tahun 2025 diprediksi akan menjadi era keemasan baru bagi industri game, menawarkan pengalaman bermain yang lebih imersif dan beragam bagi para gamer di seluruh dunia.\r\n', 'img_6820a6bf74d26.jpg', 'latest', '2025-05-11'),
(7, 'Facebook Hadirkan Tab \"Friends\" untuk Perkuat Koneksi Sosial', 'Kembalinya Ruang Khusus \"Teman\" Tanpa Algoritma yang Mengganggu!', 'Meta, perusahaan induk Facebook, mengumumkan peluncuran kembali fitur \"Friends\" tab yang dirancang untuk menampilkan konten eksklusif dari daftar teman pengguna tanpa rekomendasi tambahan. Langkah ini bertujuan untuk memfasilitasi interaksi sosial yang lebih bermakna di antara teman-teman, sejalan dengan misi awal Facebook. Awalnya tersedia di AS dan Kanada, tab ini akan menampilkan posting pribadi, Reels, cerita, pengingat ulang tahun, dan permintaan pertemanan yang tertunda. Pengguna dapat mengakses dan menyesuaikan tab baru ini melalui Home Feed atau pengaturan aplikasi. Meta berharap bahwa penekanan kembali pada koneksi pribadi akan memperkuat keterlibatan pengguna dan mengembalikan relevansi Facebook di lanskap media sosial yang padat. \r\n\r\nSelain itu, Meta memperkenalkan akun remaja baru di Facebook dan Messenger untuk meningkatkan perlindungan bagi pengguna di bawah 18 tahun. Akun ini secara otomatis membatasi interaksi, memungkinkan remaja hanya menerima pesan dari kontak yang dikenal dan membatasi visibilitas konten mereka hanya untuk teman. Fitur termasuk pengingat waktu layar, \"mode tenang\" malam hari, dan persyaratan izin orang tua untuk mengurangi pembatasan bagi mereka yang berusia di bawah 16 tahun. Perubahan ini, awalnya tersedia di AS, Inggris, Australia, dan Kanada, mengikuti pembaruan serupa di Instagram sebagai respons terhadap kekhawatiran yang meningkat dari pengawas dan pembuat undang-undang tentang kesehatan mental remaja dan sifat adiktif media sosial. ', 'img_6820a436a48b4.jpg', 'hot', '2025-05-11'),
(8, 'Metaverse Semakin Nyata: Perusahaan Teknologi Global Investasi Triliunan Rupiah', 'Bekerja, Belanja, dan Liburan di Dunia Virtual Kini Bukan Lagi Mimpi', 'Perusahaan teknologi raksasa seperti Meta, Apple, dan Google terus berlomba mengembangkan dunia metaverse, sebuah ruang virtual tiga dimensi yang memungkinkan pengguna untuk berinteraksi secara real-time. Tidak hanya sekadar hiburan, metaverse kini dilirik sebagai tempat kerja masa depan dan pasar digital yang potensial.\r\n\r\nDi Indonesia, beberapa perusahaan rintisan juga mulai mengembangkan teknologi serupa, terutama untuk sektor pendidikan dan pariwisata. Pemerintah pun menunjukkan minat besar untuk menyusun regulasi yang mendukung perkembangan teknologi ini, sekaligus melindungi masyarakat dari risiko digital seperti penipuan atau penyalahgunaan data.', 'img_6820be3c0f84c.jpeg', 'latest', '2025-05-11'),
(9, 'Aplikasi Terpopuler 2025: Dominasi AI dan Media Sosial di Era Digital', 'Tahun 2025 menandai babak baru dalam dunia aplikasi digital, dengan dominasi kecerdasan buatan (AI) dan media sosial yang semakin kuat. ', 'Tahun 2025 menandai babak baru dalam dunia aplikasi digital, dengan dominasi kecerdasan buatan (AI) dan media sosial yang semakin kuat. Data dari Appfigures menunjukkan bahwa Instagram menjadi aplikasi paling banyak diunduh secara global, dengan total 48 juta unduhan, disusul oleh TikTok, WhatsApp, dan Facebook. Menariknya, ChatGPT aplikasi berbasis AI menempati posisi kelima dengan 31 juta unduhan, menjadikannya aplikasi AI paling populer di dunia saat ini .\r\n\r\nSelain ChatGPT, aplikasi berbasis AI lainnya juga menunjukkan peningkatan signifikan. Notion AI, misalnya, membantu pengguna dalam menulis, merangkum dokumen, dan mengatur jadwal secara otomatis. Canva Magic Studio memungkinkan pembuatan desain profesional hanya dengan perintah teks, sementara Otter.ai menawarkan transkripsi real-time untuk rapat dan kuliah . Di sisi lain, aplikasi hiburan seperti Netflix, Disney+, dan Spotify tetap menjadi pilihan utama untuk streaming video dan musik .\r\n\r\nTren ini menunjukkan bahwa pengguna semakin mengandalkan aplikasi yang menggabungkan teknologi canggih dengan kemudahan penggunaan. Dengan perkembangan teknologi yang pesat, kita dapat mengantisipasi munculnya aplikasi-aplikasi baru yang lebih inovatif dan responsif terhadap kebutuhan pengguna di masa mendatang.', 'img_6820c0179187b.jpeg', 'latest', '2025-05-11'),
(10, 'Indonesia Siap Luncurkan Satelit Internet Nasional: Akses Digital Semakin Merata', 'Era Baru Internet Cepat di Pelosok Negeri Dimulai Tahun Ini', 'Pemerintah Indonesia melalui Badan Riset dan Inovasi Nasional (BRIN) bekerja sama dengan perusahaan teknologi nasional akan meluncurkan satelit internet bernama SATRIA-1 pada akhir tahun ini. Satelit ini dirancang untuk memberikan akses internet ke lebih dari 150.000 titik layanan publik seperti sekolah, puskesmas, dan kantor desa yang selama ini sulit terjangkau jaringan.\r\n\r\nLangkah ini diharapkan menjadi solusi jangka panjang dalam pemerataan akses digital, yang menjadi salah satu fokus pembangunan di era transformasi digital. Dengan peluncuran SATRIA-1, Indonesia menunjukkan keseriusannya untuk tidak hanya fokus pada kota besar, tapi juga menjangkau pelosok negeri yang selama ini terpinggirkan dalam akses teknologi.', 'img_6823392b86aeb.png', 'hot', '2025-05-09'),
(11, 'Mahasiswa Indonesia Ciptakan Drone Pintar untuk Petani', 'Teknologi Anak Bangsa Bantu Petani Tingkatkan Hasil Panen', 'Sekelompok mahasiswa dari sebuah universitas ternama di Yogyakarta menciptakan drone pintar yang mampu memetakan kondisi tanah dan menyemprotkan pupuk secara otomatis. Drone ini menggunakan teknologi pengenalan citra (image recognition) untuk mendeteksi tanaman yang memerlukan perhatian lebih.\r\n\r\nTeknologi ini memungkinkan efisiensi dalam penggunaan pupuk dan air, serta mengurangi tenaga kerja. Para petani yang telah mencoba inovasi ini menyebut hasil panen mereka meningkat hingga 30%. Inovasi ini menjadi bukti bahwa teknologi bisa memberdayakan sektor pertanian yang sering kali tertinggal dalam adopsi digital.', 'img_68233a1f3826a.jpg', 'latest', '2025-05-07'),
(12, 'Ponsel Lipat Generasi Baru Resmi Meluncur: Lebih Tipis, Lebih Tangguh', 'Inovasi Layar Fleksibel Kini Semakin Canggih dan Ramah Pengguna', 'Produsen smartphone terkemuka dunia meluncurkan ponsel lipat generasi terbaru yang lebih tipis dan lebih tahan banting. Dengan teknologi layar fleksibel generasi keempat, ponsel ini tidak hanya menawarkan tampilan yang memukau, tetapi juga daya tahan lipatan hingga lebih dari 500 ribu kali.\r\n\r\nKonsumen kini mulai melirik ponsel lipat karena multifungsinya bisa digunakan sebagai tablet maupun ponsel biasa. Daya tarik lain adalah fitur multitasking yang memungkinkan pengguna membuka tiga aplikasi sekaligus di satu layar terbuka. Teknologi ini perlahan mengubah cara orang bekerja dan berkomunikasi dari satu perangkat saja.', 'img_682339c6151d0.jpg', 'hot', '2025-05-08'),
(13, 'Revolusi Kendaraan Listrik: Motor dan Mobil Tanpa Emisi Kini Terjangkau', 'Transportasi Ramah Lingkungan Kini Bukan Hanya untuk Orang Kaya', 'Dengan meningkatnya kesadaran terhadap lingkungan dan didorong oleh kebijakan pemerintah, kendaraan listrik kini menjadi alternatif transportasi yang semakin populer di Indonesia. Beberapa produsen lokal bahkan telah merilis motor listrik dengan harga yang kompetitif, lengkap dengan sistem pengisian daya di rumah.\r\n\r\nSelain ramah lingkungan, kendaraan listrik juga lebih hemat dalam jangka panjang karena biaya operasional dan perawatan yang rendah. Pemerintah memberikan insentif tambahan seperti bebas pajak dan subsidi untuk mendorong masyarakat beralih ke kendaraan bebas emisi. Masa depan mobilitas hijau kini bukan lagi sekadar wacana, tapi sudah menjadi kenyataan yang semakin dekat.', 'img_6820be74ca726.jpeg', 'latest', '2025-05-11'),
(14, 'Startup Teknologi Lokal Bangun Aplikasi Kesehatan Berbasis AI', 'Aplikasi Ini Bisa Prediksi Penyakit Sebelum Kamu Sakit!', 'Sebuah startup teknologi asal Bandung berhasil mengembangkan aplikasi kesehatan berbasis kecerdasan buatan yang mampu memprediksi kemungkinan munculnya penyakit kronis seperti diabetes dan hipertensi. Aplikasi ini bekerja dengan menganalisis pola tidur, aktivitas fisik, serta asupan makanan pengguna melalui data dari smartwatch dan aplikasi kesehatan lainnya.\r\n\r\nTeknologi ini dianggap revolusioner karena memberikan peringatan dini kepada pengguna agar dapat melakukan tindakan pencegahan sejak awal. Selain itu, startup ini juga bekerja sama dengan sejumlah rumah sakit untuk mempercepat diagnosis penyakit berdasarkan data historis pengguna, meningkatkan efisiensi layanan kesehatan.', 'img_68233c5bcb556.jpg', 'latest', '2025-05-04'),
(15, '7 Cara Cerdas Mengikuti Perkembangan Teknologi Tanpa Harus Jadi Ahli IT', 'Mau Tetap Update di Era Digital Tapi Bingung Mulai dari Mana? Ini Tips Simpel yang Bisa Kamu Lakukan!', 'Di zaman serba digital seperti sekarang, teknologi berkembang begitu cepat. Setiap hari ada saja istilah baru: AI, blockchain, metaverse, cloud computing. Tapi tenang—kamu tidak perlu jadi programmer atau insinyur untuk bisa mengikutinya. Cukup dengan kebiasaan kecil dan konsisten, kamu bisa tetap relevan dan tak ketinggalan zaman.\r\n\r\nBerikut 7 tips sederhana agar kamu tetap update dengan dunia teknologi:\r\n\r\n1. Ikuti Media Teknologi Populer\r\nLangganan situs atau akun media sosial seperti TechCrunch, The Verge, atau detikINET. Pilih yang sesuai bahasa dan gaya kamu. Dengan membaca 5–10 menit sehari, kamu sudah bisa menangkap tren terbaru.\r\n\r\n2. Dengarkan Podcast atau Tonton YouTube Edukasi\r\nAda banyak konten ringan dan seru seputar teknologi, mulai dari review gadget sampai penjelasan AI dalam kehidupan sehari-hari. Gunakan waktu luang seperti saat di jalan untuk mendengarkannya.\r\n\r\n3. Ikut Webinar atau Workshop Gratis\r\nBanyak kampus, komunitas, dan perusahaan teknologi mengadakan pelatihan gratis. Coba cari di Eventbrite, LinkedIn, atau bahkan Instagram. Selain ilmu, kamu juga bisa menambah koneksi.\r\n\r\n4. Baca Newsletter Teknologi Mingguan\r\nBeberapa situs menyediakan rangkuman berita teknologi mingguan via email. Ini cocok kalau kamu tidak sempat mengikuti setiap hari tapi tetap ingin update.\r\n\r\n5. Gunakan Aplikasi Teknologi dalam Aktivitas Harian\r\nCoba pakai aplikasi AI seperti ChatGPT, Notion AI, atau aplikasi produktivitas berbasis cloud. Semakin sering digunakan, kamu akan semakin paham tanpa perlu belajar teori duluan.\r\n\r\n6. Tanyakan Hal Teknologi Secara Aktif\r\nJangan ragu bertanya pada teman atau lewat forum seperti Reddit, Quora, atau Komunitas Telegram. Tidak ada pertanyaan bodoh, semua orang pernah awam.\r\n\r\n7. Tetapkan Tujuan Belajar Kecil\r\nMisalnya: “bulan ini saya mau tahu dasar-dasar AI” atau “minggu ini saya belajar 1 fitur baru di Excel”. Belajar teknologi tidak harus besar-besaran, yang penting konsisten.', NULL, 'tips', '2025-05-13'),
(16, '5 Kebiasaan Digital yang Diam-Diam Membahayakan Data Pribadi Kamu', 'Sering Login Otomatis dan Pakai Wi-Fi Umum? Saatnya Lebih Waspada!', 'Dalam era serba digital ini, sebagian besar aktivitas kita bergantung pada internet mulai dari belanja online, mengakses rekening bank, sampai komunikasi pribadi. Sayangnya, di balik kenyamanan itu, ada berbagai kebiasaan digital yang justru bisa membuka celah bagi peretas untuk mencuri data kita.\r\n\r\nMisalnya, banyak orang terbiasa menyimpan kata sandi di browser, mengakses Wi-Fi publik tanpa perlindungan, atau membuka tautan mencurigakan dari email dan pesan WhatsApp. Kebiasaan ini terlihat sepele, tapi bisa membuat data pribadi seperti nomor KTP, akun bank, hingga dokumen penting dicuri dan disalahgunakan.\r\nUntuk mencegahnya, kamu bisa mulai dengan menggunakan password manager yang aman, mengaktifkan autentikasi dua langkah (2FA) di semua akun penting, serta selalu logout dari akun jika menggunakan perangkat bersama. Jangan lupa, hindari sembarang klik tautan yang tidak jelas sumbernya, dan pastikan perangkatmu selalu diperbarui agar celah keamanan tertutup.', NULL, 'tips', '2025-05-10'),
(17, 'Mengapa Teknologi AI Bukan Ancaman, Tapi Peluang Karier?', 'Jangan Takut Tersaingi Robot Ini Saatnya Jadi Teman Kerja AI!', 'Banyak orang khawatir bahwa kecerdasan buatan (AI) akan mengambil alih pekerjaan manusia. Berita tentang robot yang bisa menulis artikel, membuat musik, bahkan mendiagnosis penyakit membuat kita bertanya-tanya: “Apakah pekerjaan saya akan tergantikan?”\r\n\r\nNamun, kenyataannya tidak sesederhana itu. Teknologi AI memang akan menggantikan pekerjaan yang berulang dan rutin, tapi justru menciptakan banyak pekerjaan baru di bidang yang membutuhkan kreativitas, analisis, dan pengambilan keputusan. Peran manusia akan bergeser menjadi pengelola, pelatih, dan pengguna AI, bukan pesaingnya.\r\n\r\nContoh nyata, sekarang muncul profesi baru seperti AI Prompt Engineer, yaitu orang yang merancang instruksi untuk mendapatkan hasil terbaik dari AI. Ada juga peran AI Ethicist, yang bertugas memastikan penggunaan AI berjalan etis dan adil. Bahkan dalam bidang kreatif seperti desain, AI digunakan sebagai alat bantu, bukan pengganti.\r\n\r\nJadi, daripada takut, lebih baik mulai pelajari dasar-dasar AI dan coba gunakan dalam aktivitasmu mulai dari menulis, membuat presentasi, hingga analisis data. Dengan begitu, kamu akan jadi lebih unggul dibanding mereka yang enggan beradaptasi.', NULL, 'tips', '2025-05-12'),
(18, 'Cara Hemat Kuota Tapi Tetap Produktif Secara Digital', 'Bisa Nonton, Belajar, dan Kerja Tanpa Boros Data Internet', 'Kebutuhan internet makin besar, tapi harga paket data kadang bikin kantong bolong, apalagi bagi pelajar dan mahasiswa. Untungnya, ada cara-cara cerdas untuk tetap produktif secara digital tanpa menguras kuota.\r\n\r\nPertama, gunakan versi ringan aplikasi, seperti Facebook Lite, YouTube Go, atau TikTok Lite. Aplikasi ini dirancang untuk penggunaan data yang minimal. Kedua, aktifkan mode hemat data di browser seperti Chrome atau Opera Mini yang bisa mengompresi halaman web.\r\nKetiga, unduh konten saat terhubung ke Wi-Fi, misalnya video pembelajaran di YouTube, podcast, atau file eBook agar bisa diakses offline.\r\n\r\nKeempat, batasi update otomatis di latar belakang. Banyak aplikasi yang diam-diam menyedot kuota dengan melakukan pembaruan tanpa izin. Matikan auto-sync dan atur pembaruan aplikasi hanya saat terhubung ke Wi-Fi.\r\nTerakhir, gunakan fitur \"Data Saver\" yang tersedia di sistem Android atau iOS untuk mengontrol penggunaan data per aplikasi.\r\nDengan strategi ini, kamu bisa tetap belajar, bekerja, bahkan hiburan—tanpa takut kuota cepat habis.', NULL, 'tips', '2025-05-14'),
(19, 'Teknologi NFC Kini Digunakan untuk Pembayaran di Warung Tradisional', 'Bayar Kopi Pakai HP Tanpa Sentuh, Warung Kecil Pun Ikut Canggih', 'Teknologi Near Field Communication (NFC) yang sebelumnya hanya digunakan di pusat perbelanjaan besar kini merambah ke warung-warung tradisional. Beberapa startup fintech meluncurkan mesin pembaca NFC dengan harga murah agar UMKM bisa ikut serta dalam ekosistem pembayaran digital.\r\n\r\nLangkah ini mempermudah transaksi antara pembeli dan penjual, mengurangi risiko uang palsu, dan mencatat transaksi secara otomatis. Masyarakat pun mulai terbiasa membawa dompet digital ke mana-mana, menjadikan gaya hidup cashless semakin meluas hingga ke pelosok.', 'img_68233e2356b7d.jpeg', 'latest', '2025-05-06');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `admin`
--
ALTER TABLE `admin`
  ADD PRIMARY KEY (`id`);

--
-- Indexes for table `berita`
--
ALTER TABLE `berita`
  ADD PRIMARY KEY (`id`);

--
-- AUTO_INCREMENT for dumped tables
--

--
-- AUTO_INCREMENT for table `admin`
--
ALTER TABLE `admin`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=4;

--
-- AUTO_INCREMENT for table `berita`
--
ALTER TABLE `berita`
  MODIFY `id` int(11) UNSIGNED NOT NULL AUTO_INCREMENT, AUTO_INCREMENT=37;
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
